#!/bin/sh

EXT=".py"
DIR="/home/georgi/bin/get-shit-done"

if [ `whoami` != "root" ]
then
    # echo "Performing sudo - I need root to edit your hosts file."
    # The above message is included if anyone wants it, but it got annoying.
    sudo $0 $*
    exit $?
fi

$DIR/get-shit-done$EXT $*
